base_model: rtzr/ko-gemma-2-9b-it
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
token: # 허깅페이스 토큰

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: cpm-ai/ai_malpyung_ilsang_train_dev
    type: alpaca
    drop_system_message: true
val_set_size: 0.0
output_dir: ./outputs/qlora_output

adapter: qlora
lora_r: 64
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true

sequence_len: 4096
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: true

wandb_project: 일상대화요약_나
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:


gradient_accumulation_steps: 2
micro_batch_size: 4
num_epochs: 10
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_ratio: 0
evals_per_epoch:
eval_table_size:
eval_max_new_tokens: 0
saves_per_epoch: 0
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
